parameters:

    #default value in case it's not overiden in parameters.yml
    front_end_path:    http://localhost/asre/frontend/app/#/
    front_end_confirm_path:    confirm
    front_end_reset_path:    reset

    routing_dev_file:  routing_dev.yml

    locale:            en
    secret:            ThisTokenIsNotSoSecretSoChangeIt

    bootstrap_source:  http://twitter.github.com/bootstrap/assets/bootstrap.zip
    max_per_page:      20

    path_to_node:      /usr/local/bin/node

    fos_oauth_server.user_provider: asre_oauth_server.user.provider



    social_networks:
        google:
            type:                google
            client_id:           %google.client_id%
            client_secret:       %google.client_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                 access_type:     offline
                 approval_prompt: auto
                 display:         popup
                 login_hint:      email address
        twitter:
            type:                twitter
            client_id:           %twitter.client_id%
            client_secret:       %twitter.client_secret%
        facebook:
            type:                facebook
            client_id:           %facebook.client_id%
            client_secret:       %facebook.client_secret%
            scope:               "email"
            options:
                 display:         popup
        linkedin:
            type:                linkedin
            client_id:           %linkedin.client_id%
            client_secret:       %linkedin.client_secret%            scope:               r_fullprofile
            infos_url:           "http://api.linkedin.com/v1/people/~:(id,formatted-name,recommendations-received)"