jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
       # Symfony\Component\Security\Core\User\User: plaintext
        asre\SecurityBundle\Entity\User:
         # id : fos_user.password_provider.encoder
          algorithm: sha512
          iterations: 1
          encode_as_base64: false

    providers:
        main:
            id: fos_user.user_provider.username
        oauth_provider:
            id: asre_oauth_server.user.provider

#        in_memory:
#            memory:
#                users:
#                    #define here the user password of the "admin" account
#                    admin: { password: wwwconfTER, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/account/login$
            anonymous: true # On autorise les anonymes sur ce pare-feu

        oauth_login:
            pattern:   ^/account/connect
            anonymous: true # On autorise les anonymes sur ce pare-feu

        oauth_token:
            pattern:    ^/account/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern: ^/account/oauth/v2/auth
            form_login:
                provider: oauth_provider
                check_path: /account/oauth/v2/auth_login_check
                login_path: /account/oauth/v2/auth_login
#                success_handler: asre_oauth_server.authentication_handler
#                failure_handler: asre_oauth_server.authentication_handler
            anonymous: true

        api:
            pattern:   ^/api
            fos_oauth: true
            stateless: true

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            fos_oauth:  true
            stateless:  true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            form_login:
#               login_path: fos_user_security_login
#               check_path: fos_user_security_check
                login_path: /account/login
                check_path: /account/login/login_check
                default_target_path: dashboard_index
                success_handler: authentication_handler
                failure_handler: authentication_handler
                require_previous_session: false # The default value is true
                #
            oauth:
                resource_owners:
                    google:         "/account/login/check-google"
                    twitter:        "/account/login/check-twitter"
                    facebook:       "/account/login/check-facebook"
                    linkedin:       "/account/login/check-linkedin"
                login_path:        /account/login
                failure_path:      /account/login
                default_target_path: /
                use_forward:       false
                success_handler: authentication_handler
#                failure_handler: authentication_handler
                # use_forward:       true

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: fosub_user_provider
            logout:
                success_handler: asre.rest.logout.success_handler
                path:   logout
                target: /

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/account/oauth/v2/auth$, role: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#            - { path: ^/account/oauth/v2/auth_login, role: IS_AUTHENTICATED_ANONYMOUSLY}
#            - { path: ^/account/oauth/v2/auth, roles: ROLE_USER }

