<?php


namespace asre\SecurityBundle\Repository;

use asre\SecurityBundle\Entity\Team;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class UserRepository extends EntityRepository
{
}
